{% set name = "llguidance" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f1371639ff1e96b1cb4e60ad64b8e514a533b12025e83954025c79c5c9cad8f7

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - llguidance
  commands:
    - pip check
    - abi3audit $SP_DIR/llguidance/_lib.abi3.so -s -v --assume-minimum-abi3 {{ python }}   # [unix]
    - abi3audit %SP_DIR%/llguidance/_lib.pyd -s -v --assume-minimum-abi3 {{ python }}      # [win]
  requires:
    - pip
    - abi3audit

about:
  home: https://github.com/guidance-ai/llguidance
  summary: Bindings for the Low-level Guidance (llguidance) Rust library for use within Guidance
  description: |
    This library implements constrained decoding (also called constrained sampling
    or structured outputs) for Large Language Models (LLMs). It can enforce
    arbitrary context-free grammar on the output of LLM and is fast - on the
    order of 50μs of CPU time per token (for 128k tokenizer) with negligible
    startup costs.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - parser/LICENSE
    - toktrie_hf_tokenizers/LICENSE
    - toktrie_hf_downloader/LICENSE
    - toktrie/LICENSE
    - THIRDPARTY.yml
  doc_url: https://github.com/guidance-ai/llguidance
  dev_url: https://github.com/guidance-ai/llguidance

extra:
  recipe-maintainers:
    - shermansiu
